### ISSUE TITLE
Spike with https://www.asyncapi.com/

### ISSUE THREAD

**Issue by torrespro** [Backbase/golden-sample-services#49]
Use Asynapi to define our events and generate code from them if possible

We want to define those events using https://www.asyncapi.com/ in a similar way we define the APIs with OpenAPI.

https://github.com/asyncapi/java-spring-cloud-stream-template

**Comment by polarfish** [comment]
I am closing this issue because it is not relevant anymore. Another custom approach for documenting events has been taken in favour of AsyncAPI.
