### ISSUE TITLE
Introduce Multitenancy

### ISSUE THREAD

**Issue by torrespro** [Backbase/golden-sample-services#6]
We want a set up when we show how to use Multitenancy in all the possible variations:
- Data isolation
- Config isolation
- Filesystem isolation
- Cache isolation

https://community.backbase.com/documentation/ServiceSDK/latest/multitenancy_configuration
https://backbase.atlassian.net/wiki/spaces/GUIL/pages/2027880530/Multitenancy

**Comment by jamespatten755** [comment]
Unsure if we can / need to demonstrate filesystem isolation.

**Comment by eacarvalho** [comment]
Thinking about it and I guess we have 2 approaches to deal with this ticket:

**1.** Add multi-tenancy dependencies and configure all the services to use multi-tenancy and for each service:
```
- Add 2 tenants then 2 databases per service;
- Changes in yaml files adding the tenants configuration;
- In case there is public resource than add NGINX as reverse proxy to set X-TID header;
```

**2.** Add multi-tenancy dependencies and only in the Spring Boot Integration Tests configure multi-tenancy properties:
```
- Create yaml which will run considering specific multi-tenancy profile per service;
- This involves smaller changes but developers still can understand how to configure properties looking in the tests;
```

Please which of 2 approaches should we go?

**Comment by jjjasper** [comment]
https://github.com/Backbase/golden-sample-services/pull/59 added m10y support.
